### PR TITLE
23 gamedeals command doesnt respond when given certain inputs

### LINKED ISSUE #23: Gamedeals command doesn't respond when given certain inputs
**Describe the bug**
The command `/gamedeals title: Dead Space country: Canada` fails to respond.

**To Reproduce**
As above

**Expected behavior**
It should either respond with game deal information or an error message

### PR DESCRIPTION
**Pull request by darrenfoley**

### CODE REVIEW

File: src/Asiago/Core/IsThereAnyDeal/IsThereAnyDealClient.cs [hunk 1]
```diff
@@ -1,16 +1,21 @@
...
+using Asiago.Extensions;
+using Microsoft.Extensions.Options;
 using Newtonsoft.Json;
-using System.Net.Http.Json;
 
-namespace IsThereAnyDeal
+namespace Asiago.Core.IsThereAnyDeal
 {
-    public class IsThereAnyDealClient(string apiKey, HttpClient httpClient)
+    internal class IsThereAnyDealClient(
```
Comment (darrenfoley) [inline src/Asiago/Core/IsThereAnyDeal/IsThereAnyDealClient.cs]: Don't use primary constructor

File: src/Asiago/SlashCommands/IsThereAnyDealModule.cs [hunk 2]
```diff
@@ -1,25 +1,16 @@
...
 using DSharpPlus.Entities;
 using DSharpPlus.SlashCommands;
-using IsThereAnyDeal;
-using IsThereAnyDeal.Models;
-using Microsoft.Extensions.Options;
 
 namespace Asiago.SlashCommands
 {
-    internal class IsThereAnyDealModule : ApplicationCommandModule
+    internal class IsThereAnyDealModule(IsThereAnyDealClient itadClient) : ApplicationCommandModule
```
Comment (darrenfoley) [inline src/Asiago/SlashCommands/IsThereAnyDealModule.cs]: Don't use primary constructor

File: src/Asiago/SlashCommands/IsThereAnyDealModule.cs [hunk 3]
```diff
@@ -128,24 +118,16 @@ internal enum Country
         US,
     }
 
-    internal class GameTitleAutocompleteProvider : IAutocompleteProvider
+    internal class GameTitleAutocompleteProvider(IsThereAnyDealClient itadClient) : IAutocompleteProvider
```
Comment (darrenfoley) [inline src/Asiago/SlashCommands/IsThereAnyDealModule.cs]: Don't use primary constructor
